NumPy(Numeric Python) -> Helps to manipulate large arrays and matrices of numeric data.

In [2]:
import numpy
a = numpy.array([1,2,3,4,5])
print(a[0])
b = numpy.array([1,2,3,4,5],float)
print(b[1])

1
2.0


In [7]:
# Python Slice operation

# a[start:end:step]

for i in range(10)[::2]:
    print(i)

0
2
4
6
8


In [8]:
import numpy

def arrays(a): # Function Definition
    a = a[::-1] # reverse the list
    a = list(map(float,a)) # Convert the list of string to float datatype
    a = numpy.array(a)
    return a

# Function Definition
a = input().strip().split() # Split by blank spaces
r  = arrays(a) # Function Declaration
print(r)

1 2 3 4 5
[ 5.  4.  3.  2.  1.]


In [10]:
import numpy

def arrays(a): # Function Definition
   return(numpy.array(a,float)[::-1])

# Function Definition
a = input().strip().split() # Split by blank spaces
r  = arrays(a) # Function Declaration
print(r)

1 2 3 4 5
[ 5.  4.  3.  2.  1.]


In [14]:
# shape tool -> Give tuple of array dimensions and can be used to change dimensions of the array

# Using shape to get array dimensions

import numpy
my_1d = numpy.array([1,2,3,4,5])
print(my_1d.shape) # (5,) -> 5 rows and 0 columns

my_2d = numpy.array([[1,2],[3,4],[5,6]])
print(my_2d.shape) # (3,2) -> 3 rows and 2 columns

(5,)
(3, 2)


In [15]:
# Using shape to change the array dimension
import numpy
change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3,2)
print(change_array)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
# Using reshape-> gives newshape and without changing its data
import numpy
my_array_2 = numpy.array([1,2,3,4,5,6])
print(numpy.reshape(my_array_2,(3,2)))
print(my_array_2)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [18]:
import numpy

s = input().strip().split() # Split input by blank spaces

a = list(map(int,s))import numpy

n,m  = map(int,input().split())
a = list()
for i in range(0,n):
    a1 = list(map(int,input().split()))
    a.append(a1)
a = numpy.array(a)
print(numpy.transpose(a))
print(a.flatten())
a = numpy.array(a)
a.shape = (3,3)
print(a)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
import numpy

n,m  = map(int,input().split())
a = list()
for i in range(0,n):
    a1 = list(map(int,input().split()))
    a.append(a1)
a = numpy.array(a)
print(numpy.transpose(a))
print(a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [27]:
import numpy

n1,m1 = map(int,input().split())
a1 = numpy.array([input().strip().split() for _ in range(n1)],int)
print(a1.transpose())
print(a1.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [25]:
# '_' (underscore) variable in python consides as 'I dont care' 
# or 'Throwaway' variable in python used for ignoring specific values

# Used for ignoring specific values

(x,_,y)=(1,2,3)
print(x)
print(y)

# Ignoring the index

for _ in range(2):
    print("Hello World!")

1
3
Hello World!
Hello World!


In [41]:
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

print(numpy.concatenate((array_1, array_2, array_3)))    

[1 2 3 4 5 6 7 8 9]


In [53]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0],[1,2,3]])
array_2 = numpy.array([[0,0,0],[7,8,9],[1,2,3]])

print(numpy.concatenate((array_1, array_2), axis = 1))   

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]
 [1 2 3 1 2 3]]


In [58]:
n,m,p = map(int,input().strip().split())
array_1 = list()
array_2 = list()
for _ in range(n):
    a = list(map(int,input().strip().split()))
    array_1.append(a)
    
for _ in range(m):
    a = list(map(int,input().strip().split()))
    array_2.append(a)

array_1 = numpy.array(array_1)
array_2 = numpy.array(array_2)
print(numpy.concatenate((array_1,array_2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
1 2
1 2
1 2
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]


In [63]:
# zeros

# The zeros tool returns a new array with a given shape and type filled with 's.
import numpy
print(numpy.zeros((1,2)))     # Type change into float

[[ 0.  0.]]


In [66]:
# ones

# The ones tool returns a new array with a given shape and type filled with 1's.
import numpy
print(numpy.ones((1,2),dtype=numpy.int)) # Type change into int

[[1 1]]


In [67]:
import numpy
nums = list(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [70]:
# identity

# The identity tool returns an identity array. An identity array is a square 
# matrix with all the main diagonal elements as  1 and the rest as 0. The default type of elements is float.

import numpy
print(numpy.identity(3)) #3 is for  dimension 3 X 3

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [75]:
# eye

# The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. 
# The diagonal can be main, upper or lower depending on the optional parameter k . 
# A positive k is for the upper diagonal, a negative k is for the lower, and a 0 k   (default) is for the main diagonal.
import numpy
print(numpy.eye(8, 7, k = 2))    # 8 X 7 Dimensional array with first upper diagonal 1.

[[ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [76]:
import numpy
m,n = map(int,input().strip().split())
print(numpy.eye(m, n, k = 0))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [78]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print(a + b)                     #[  6.   8.  10.  12.]
print(numpy.add(a, b))           #[  6.   8.  10.  12.]

print(a - b)                     #[-4. -4. -4. -4.]
print(numpy.subtract(a, b))      #[-4. -4. -4. -4.]

print(a * b)                     #[  5.  12.  21.  32.]
print(numpy.multiply(a, b))      #[  5.  12.  21.  32.]

print(a / b)                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print(numpy.divide(a, b))        #[ 0.2         0.33333333  0.42857143  0.5       ]

print(a % b)                     #[ 1.  2.  3.  4.]
print(numpy.mod(a, b))           #[ 1.  2.  3.  4.]

print(a**b)                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print(numpy.power(a, b))        #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]

[  6.   8.  10.  12.]
[  6.   8.  10.  12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[  5.  12.  21.  32.]
[  5.  12.  21.  32.]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


In [80]:
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print(numpy.sum(my_array, axis = 0) )        #Output : [4 6]
print(numpy.sum(my_array, axis = 1)  )       #Output : [3 7]
print(numpy.sum(my_array, axis = None))      #Output : 10
print(numpy.sum(my_array))                   #Output : 10

[4 6]
[3 7]
10
10


In [84]:
import numpy
n,m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
print( numpy.prod( numpy.sum(a, axis = 0),axis = 0))



2 2
1 2
3 4
24


In [85]:
import numpy
n,m = map(int,input().strip().split())
a = numpy.array([input().split() for _ in range(n)],int)
print(numpy.max(  numpy.min(a, axis = 1)))



4 2
2 5
3 7
1 3
4 0
3
